INSERT INTO diretores (nome) VALUES
('Quentin Tarantino'),
('Steven Spielberg'),
('Christopher Nolan'),
('Martin Scorsese'),
('Francis Ford Coppola'),
('Pedro Almodóvar'),
('Akira Kurosawa'),
('Federico Fellini'),
('Stanley Kubrick'),
('Alfred Hitchcock'),
('Woody Allen'),
('Tim Burton'),
('Guillermo del Toro'),
('David Lynch'),
('Michael Haneke'),
('Lars von Trier'),
('Chan-wook Park'),
('Alejandro González Iñárritu'),
('Denis Villeneuve'),
('Bong Joon-ho');

INSERT INTO generos (nome) VALUES
('Drama'),
('Comédia'),
('Ação'),
('Aventura'),
('Ficção Científica'),
('Fantasia'),
('Terror'),
('Romance'),
('Documentário'),
('Animação'),
('Musical'),
('Guerra'),
('História'),
('Biografia'),
('Crime'),
('Suspense'),
('Família'),
('Drama Familiar'),
('Comédia Romântica');


INSERT INTO avaliacoes (valor) VALUES
(4.5),
(4.2),
(5.0),
(3.9),

(4.8),
(4.1),
(5.0),
(4.6),
(3.7),
(4.9),
(4.3),
(4.4),
(5.0),
(3.8),
(4.7),
(4.2),
(4.5),
(4.9),
(5.0),
(4.6);

INSERT INTO filmes (titulo, id_diretor, id_genero, id_avaliacao) VALUES
('Pulp Fiction', 1, 1, 1),
('O Resgate do Soldado Ryan', 2, 1, 2),
('Batman: O Cavaleiro das Trevas', 3, 1, 3),
('Os Bons Companheiros', 1, 1, 4),
('Apocalipse Now', 5, 1, 5),
('Mulheres à Beira de um Ataque de Nervos', 6, 2, 6),
('Os Sete Samurais', 7, 3, 7),
('La Dolce Vita', 8, 2, 8),
('2001: Uma Odisseia no Espaço', 9, 4, 9),
('Psicose', 10, 5, 10),
('Annie Hall', 11, 2, 11),
('O Estranho Mundo de Jack', 12, 6, 12),
('O Labirinto do Fauno', 13, 1, 13),
('Twin Peaks: O Retorno', 14, 5, 14),
('Caché', 15, 15, 15),
('Anticristo', 16, 16, 16),
('Parasita', 17, 17, 17),
('O Regresso', 18, 1, 18),
('Parasita', 19, 17, 19),
('O Farol', 20, 14, 20);
